name: Check Flood Forecast

on:
  schedule:
    - cron: '15 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  actions: write

concurrency:
  group: flood-forecast-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flood-forecast:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip
        cache-dependency-path: proton-version-check/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check Flood Forecast
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_SENDER_EMAIL: ${{ secrets.SMTP_SENDER_EMAIL }}
        SMTP_NOTIFY_MAIL: ${{ secrets.SMTP_NOTIFY_MAIL }}
      run: |
        python flood-alert/check-flood-forecast.py

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 14
        keep_minimum_runs: 6


