name: Check Proton app versions  

on:  
  schedule:  
    - cron: '30 * * * *'  
  workflow_dispatch:  

permissions:
  contents: write
  issues: write
  actions: write

concurrency:
  group: version-check-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  proton-drive-version-check:  
    runs-on: ubuntu-latest  
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v5  

    - name: Set up Python  
      uses: actions/setup-python@v5  
      with:  
        python-version: '3.x'  
        cache: pip
        cache-dependency-path: proton-version-check/requirements.txt

    - name: Install dependencies  
    
      working-directory: proton-version-check  
      run: pip install -r requirements.txt

    - name: Check Version  
      id: check_version  
      working-directory: proton-version-check  
      run: |     
        python check-proton-app-versions.py

    - name: Commit and Push if any version changed  
      run: |  
        git config --local user.name 'traktuner'  
        git config --local user.email 'traktuner@users.noreply.github.com'  
        git add .  
        git diff --staged --quiet || git commit -m "Update last_version files"  
        git push  

    - name: Delete workflow runs  
      uses: Mattraks/delete-workflow-runs@v2  
      with:  
        token: ${{ secrets.GITHUB_TOKEN }}  
        repository: ${{ github.repository }}  
        retain_days: 14  
        keep_minimum_runs: 6