name: Check Proton Drive macOS Version

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  version-check-macos:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Check Version
      id: check_version
      run: |
        python check-proton-drive-macos-version.py
      working-directory: proton-drive-version-check

    - name: Commit and Push if version changed
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        git config --global user.name 'traktuner'
        git config --global user.email 'traktuner@users.noreply.github.com'
        git add last_version_macos.txt
        git commit -m "Update last_version_macos.txt to ${{ steps.check_version.outputs.current_version }}"
        git push
      working-directory: proton-drive-version-check

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 6