name: Check Proton Drive macOS Version

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  version-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check Version
      run: |
        python proton-drive-version-check/check-proton-drive-macos-version.py
      working-directory: proton-drive-version-check

    - name: Commit and Push if version changed
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        git config --global user.name 'traktuner'
        git config --global user.email 'traktuner@users.noreply.github.com'
        git add last_version.txt
        git commit -m "Update last_version.txt to ${current_version}"
        git push
      working-directory: proton-drive-version-check
