name: Mirror GitLab to GitHub

on:
  schedule:
    - cron: '23 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: mirror-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitLab Repository
        run: |
          git clone --mirror https://gitlab.rrze.fau.de/faumac/networkShareMounter.git
      - name: Push to GitHub Repository
        run: |
          cd networkShareMounter.git
          git push --mirror "https://${{ secrets.GH_PAT }}@github.com/traktuner/networkShareMounter.git"
